#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import csv
import numpy as np

import imfusion as imf
import imfusion.ultrasound as us


# Configuration values used by this script.
# The CSV is expected to contain one pose per row in the ImFusion world frame:
# x, y, z, qx, qy, qz, qw (positions in mm, quaternion in x/y/z/w).
CSV_PATH = r"/home/chiararipiemo/validation/Test_3/best_pose_2/10.us_best_pose_imfusion.csv"
# CSV_PATH = r"/home/chiararipiemo/validation/Test_3/apex_pose/10.us_apex_pose_imfusion.csv"

CSV_UNITS = "mm"  # ImFusion typically uses millimeters

SWEEP_NAME = "Sweep from CSV (quaternion driven, convex)"
SWEEP_TIME_S = 3.0  # Total sweep duration; timestamps are distributed uniformly over this time

# Dummy image size (pixels). These frames are placeholders; the sweep geometry/tracking drives placement.
IMG_W = 128
IMG_H = 200

# Attempt to set convex probe geometry metadata from Python.
# Depending on the ImFusion version/API bindings, these fields may not be exposed and you may need to set them in the GUI.
USE_CONVEX_GEOMETRY = True
PROBE_WIDTH_MM = 38.0
DEPTH_MM = 120.0
OPENING_ANGLE_DEG = 60.0
LONG_RADIUS_MM = 100.0

# If True, the sweep is positioned so that the top of the image corresponds to the probe tip.
# The script achieves this by shifting the image center by DEPTH/2 along the beam direction.
START_AT_PROBE_TIP = True

# Default offset along the beam direction (mm) used when START_AT_PROBE_TIP is False.
OFFSET_ALONG_BEAM_MM = 30.0

# Probe-to-image axes mapping in the local probe frame used by the CSV poses.
# The script assumes the ultrasound beam points along +Z in the probe local frame.
PROBE_DEPTH_AXIS_LOCAL = np.array([0.0, 0.0, 1.0], dtype=float)   # Beam/depth direction (blue axis)
PROBE_LATERAL_AXIS_LOCAL = np.array([1.0, 0.0, 0.0], dtype=float) # Lateral direction (red axis)

# If the CSV contains only one pose, ImFusion tracking needs at least two timestamps to form a sequence.
# When enabled, the script duplicates the single pose and applies a small lateral shift.
DUPLICATE_SINGLE_POSE = True
DUPLICATE_SHIFT_MM = 0.1


def ensure_app():
    """
    Ensure an ImFusion app/controller exists.

    If the script is executed outside ImFusion Suite, imf.app may be missing.
    In that case we create a ConsoleController so that we can still construct
    data objects and add them to the data model.
    """
    if not getattr(imf, "app", None):
        imf.app = imf.ConsoleController()


def normalize(v):
    """
    Return a unit-length version of v with a small epsilon to avoid division by zero.
    """
    v = np.asarray(v, dtype=float)
    return v / (np.linalg.norm(v) + 1e-12)


def quat_to_rotmat(qx, qy, qz, qw):
    """
    Convert a quaternion (x, y, z, w) into a 3x3 rotation matrix.

    The quaternion is normalized before conversion. If the quaternion is near-zero,
    the identity rotation is returned.
    """
    q = np.array([qx, qy, qz, qw], dtype=float)
    n = np.linalg.norm(q)
    if n < 1e-12:
        return np.eye(3, dtype=float)
    q /= n
    x, y, z, w = q

    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z

    R = np.array(
        [
            [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz),       2.0 * (xz + wy)],
            [2.0 * (xy + wz),       1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx)],
            [2.0 * (xz - wy),       2.0 * (yz + wx),       1.0 - 2.0 * (xx + yy)],
        ],
        dtype=float,
    )
    return R


def load_csv_poses(csv_path, units="mm"):
    """
    Load poses from a CSV file.

    The expected CSV format is one pose per row (with an optional header):
      x, y, z, qx, qy, qz, qw

    Positions are interpreted in millimeters by default. If units == "m",
    positions are converted to millimeters.

    The return value is a list of dicts:
      { "p": np.array([x,y,z]), "R": 3x3 rotation matrix }

    If the CSV contains only one pose and DUPLICATE_SINGLE_POSE is True,
    a second pose is generated by shifting the position slightly along the
    probe lateral direction in world coordinates, keeping the same rotation.
    """
    if not os.path.exists(csv_path):
        raise RuntimeError("CSV not found: %s" % csv_path)

    out = []
    with open(csv_path, "r") as f:
        r = csv.reader(f)
        _ = next(r, None)  # skip header if present
        for row in r:
            if not row or len(row) < 7:
                continue
            try:
                vals = [float(v) for v in row[:7]]
            except ValueError:
                continue

            x, y, z, qx, qy, qz, qw = vals

            if units.lower() == "m":
                x, y, z = 1000.0 * x, 1000.0 * y, 1000.0 * z

            R = quat_to_rotmat(qx, qy, qz, qw)
            p = np.array([x, y, z], dtype=float)
            out.append({"p": p, "R": R})

    if not out:
        raise RuntimeError("No valid poses found in CSV.")

    if len(out) == 1 and DUPLICATE_SINGLE_POSE:
        p0 = out[0]["p"].copy()
        R0 = out[0]["R"].copy()

        # Convert the probe lateral axis from local probe coordinates into world coordinates
        lateral_world = normalize(R0 @ PROBE_LATERAL_AXIS_LOCAL)

        # Shift the duplicated pose slightly to create a minimal two-sample tracking sequence
        p1 = p0 + lateral_world * float(DUPLICATE_SHIFT_MM)
        out.append({"p": p1, "R": R0})

    return out


def create_empty_image():
    """
    Create a dummy ultrasound image frame.

    The image content is not used here; the purpose is to populate the sweep with frames
    so that ImFusion can display a sweep object. Physical spacing is set for visualization.
    Probe geometry (e.g., convex) is handled via metadata if available.
    """
    img_desc = imf.ImageDescriptor(imf.PixelType.UBYTE, IMG_W, IMG_H, 1, 1)
    img_desc.spacing = np.array([0.5, 0.5, 1.0], dtype=float)
    img_desc.is_metric = True
    return imf.SharedImage(imf.MemImage(img_desc))


def remove_existing_by_name(name):
    """
    Remove existing data model entries with the same name to avoid duplicates.
    """
    to_remove = [d for d in imf.app.data_model if getattr(d, "name", "") == name]
    for d in to_remove:
        try:
            imf.app.data_model.remove(d)
        except Exception:
            pass


def get_components(obj):
    """
    Return a list of components attached to an ImFusion object.

    Different ImFusion versions/bindings expose components differently; this helper wraps access safely.
    """
    try:
        return list(obj.components)
    except Exception:
        return []


def add_component_best_effort(sweep, comp):
    """
    Attach a component to a sweep using the first available API method.

    ImFusion bindings may expose different names for the same action. This helper tries common ones
    and falls back to appending into sweep.components if that is a mutable list.
    """
    for m in ("add_component", "addComponent", "add"):
        if hasattr(sweep, m):
            try:
                getattr(sweep, m)(comp)
                return True
            except Exception:
                pass
    try:
        sweep.components.append(comp)
        return True
    except Exception:
        return False


def get_or_create_frame_geometry_metadata(sweep):
    """
    Retrieve an existing FrameGeometryMetadata component from the sweep or create one.

    If the Python bindings do not allow constructing or attaching this metadata, the function
    returns None and the user may need to configure geometry manually in the GUI.
    """
    for c in get_components(sweep):
        if isinstance(c, us.FrameGeometryMetadata):
            return c

    try:
        fgm = us.FrameGeometryMetadata()
    except Exception as e:
        print("Geometry: cannot construct FrameGeometryMetadata:", e)
        return None

    ok = add_component_best_effort(sweep, fgm)
    if not ok:
        print("Geometry: could not attach FrameGeometryMetadata to sweep (API mismatch).")
        return None

    return fgm


def configure_convex_geometry(sweep):
    """
    Try to configure convex probe geometry for the sweep.

    This is best-effort because ImFusion Python bindings may not expose the necessary fields
    depending on version. If fields are not available, the script prints instructions to set
    geometry via the GUI (Frame Geometry Properties).
    """
    fgm = get_or_create_frame_geometry_metadata(sweep)
    if fgm is None:
        print("Geometry: no FrameGeometryMetadata available on this sweep.")
        print("Geometry: set Convex geometry in GUI (Frame Geometry Properties).")
        return

    fg = None
    if hasattr(fgm, "frame_geometry"):
        fg = fgm.frame_geometry
    elif hasattr(fgm, "frameGeometry"):
        fg = fgm.frameGeometry

    if fg is None:
        print("Geometry: FrameGeometryMetadata has no frame_geometry (None).")
        print("Geometry: set Convex in GUI: right click sweep -> Frame Geometry Properties.")
        return

    set_any = False

    # Depth of the convex sector (mm)
    if hasattr(fg, "depth"):
        fg.depth = float(DEPTH_MM)
        set_any = True

    # Opening angle and radii (if exposed by the bindings)
    if hasattr(fg, "opening_angle"):
        fg.opening_angle = float(OPENING_ANGLE_DEG)
        set_any = True

    if hasattr(fg, "long_radius"):
        fg.long_radius = float(LONG_RADIUS_MM)
        set_any = True

    # Some models expose short_radius; derive it from probe width and opening angle when possible
    if hasattr(fg, "short_radius") and hasattr(fg, "opening_angle"):
        fg.short_radius = float(PROBE_WIDTH_MM) / (2.0 * np.sin(np.deg2rad(float(OPENING_ANGLE_DEG))))
        set_any = True

    # Keep width if available
    if hasattr(fg, "width"):
        fg.width = float(PROBE_WIDTH_MM)
        set_any = True

    # Prefer a top-down display if supported
    if hasattr(fg, "top_down"):
        fg.top_down = True
        set_any = True

    if set_any:
        print("Geometry: convex parameters applied where supported.")
    else:
        print("Geometry: this frame_geometry does not expose convex fields in Python.")
        print("Geometry: please set Convex in GUI (Frame Geometry Properties on the sweep).")


def build_image_pose(p_world, R_probe_to_world, offset_along_beam_mm):
    """
    Build a 4x4 transform placing an ultrasound image plane in the ImFusion world.

    The CSV provides the probe pose (probe-to-world rotation and probe tip position). This function
    defines an image coordinate frame based on two probe axes:
      - Image X axis is the probe lateral axis
      - Image Y axis is the beam/depth axis (pointing away from the probe)
      - Image Z axis is the right-handed cross product completing the basis

    The translation is placed at p_world plus an offset along the beam direction. When START_AT_PROBE_TIP
    is enabled, the offset is typically DEPTH/2 so that the top edge of the image aligns with the probe tip.
    """
    x_axis = normalize(R_probe_to_world @ PROBE_LATERAL_AXIS_LOCAL)  # image X axis in world
    y_axis = normalize(R_probe_to_world @ PROBE_DEPTH_AXIS_LOCAL)    # image Y axis (beam) in world

    # Build a right-handed orthonormal basis
    z_axis = normalize(np.cross(x_axis, y_axis))
    x_axis = normalize(np.cross(y_axis, z_axis))

    T = np.eye(4, dtype=float)
    T[:3, 0] = x_axis
    T[:3, 1] = y_axis
    T[:3, 2] = z_axis

    # Position the image center along the beam direction
    T[:3, 3] = p_world + y_axis * float(offset_along_beam_mm)
    return T


def main():
    """
    Create an ImFusion UltrasoundSweep from a CSV tracking sequence.

    For each pose in the CSV:
      - a dummy image frame is appended to the sweep
      - a corresponding tracking transform (image pose in world) is added with a timestamp

    At the end, the sweep is pushed into the ImFusion data model so it appears in the workspace.
    """
    ensure_app()

    poses = load_csv_poses(CSV_PATH, units=CSV_UNITS)
    n = len(poses)
    print("Loaded poses:", n)

    if n < 2:
        raise RuntimeError("Need at least 2 poses (enable DUPLICATE_SINGLE_POSE or provide more rows).")

    # Choose the offset along the beam direction.
    # If we want the top of the image at the probe tip, we place the image center at DEPTH/2.
    offset_mm = float(OFFSET_ALONG_BEAM_MM)
    if START_AT_PROBE_TIP:
        offset_mm = 0.5 * float(DEPTH_MM)

    remove_existing_by_name(SWEEP_NAME)

    sweep = us.UltrasoundSweep()
    sweep.name = SWEEP_NAME

    tracking = imf.TrackingSequence()

    # Uniformly distribute timestamps between 0 and SWEEP_TIME_S
    dt = float(SWEEP_TIME_S) / float(n - 1)

    for i in range(n):
        t = i * dt
        p = poses[i]["p"]
        R = poses[i]["R"]

        # Convert the probe pose into an image pose (the transform used by the sweep tracking)
        T_img = build_image_pose(p, R, offset_mm)

        # Add transform to tracking: (transform, time, quality)
        tracking.add(T_img, t, 1.0)

        # Add a dummy image frame and set its timestamp when supported
        sweep.add(create_empty_image())
        try:
            sweep.set_timestamp(t, sweep.size - 1)
        except Exception:
            pass

    # Attach tracking to the sweep
    sweep.add_tracking(tracking)

    # Prefer top-down visualization when the property exists
    try:
        sweep.properties.set_param("topDown", True)
    except Exception:
        pass

    # Try to configure convex probe geometry metadata (best-effort)
    if USE_CONVEX_GEOMETRY:
        configure_convex_geometry(sweep)

    # Add sweep to ImFusion workspace
    imf.app.data_model.add(sweep)

    print("OK: sweep added:", SWEEP_NAME)
    print("Offset along beam (mm):", offset_mm)
    print("If the image is mirrored, flip PROBE_LATERAL_AXIS_LOCAL sign.")


if __name__ == "__main__":
    main()

